// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57K5rNFvdBTdmjIZ6bo_eXlD8PQLhF8Q',
    appId: '1:795957960549:web:670ad49f04b52e69c90b8c',
    messagingSenderId: '795957960549',
    projectId: 'signin-mcm',
    authDomain: 'signin-mcm.firebaseapp.com',
    storageBucket: 'signin-mcm.appspot.com',
    measurementId: 'G-RWJQ2SCXR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsQPcPLYs1pcvNSk0sx_FASvBT60QxvMs',
    appId: '1:795957960549:android:c3a972a6be6c465ec90b8c',
    messagingSenderId: '795957960549',
    projectId: 'signin-mcm',
    storageBucket: 'signin-mcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAct7kdkEVQg6NUXY3w3Z7u6TZ0J2NHKLY',
    appId: '1:795957960549:ios:dd223405d8a295bcc90b8c',
    messagingSenderId: '795957960549',
    projectId: 'signin-mcm',
    storageBucket: 'signin-mcm.appspot.com',
    iosBundleId: 'com.example.miniProMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAct7kdkEVQg6NUXY3w3Z7u6TZ0J2NHKLY',
    appId: '1:795957960549:ios:dd223405d8a295bcc90b8c',
    messagingSenderId: '795957960549',
    projectId: 'signin-mcm',
    storageBucket: 'signin-mcm.appspot.com',
    iosBundleId: 'com.example.miniProMain',
  );
}
